const REPO="BijranTahir/BijranTahir.github.io",BRANCH="main";
const FILES={profile:"profile.json",research:"research.json",projects:"projects.json",library:"library.json",content:"content.json",timeline:"timeline.json",categories:"categories.json"};
const defaults={profile:{},research:[],projects:[],library:[],content:[],timeline:[],categories:[]};let token="",data={},sha={};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function toast(m){const e=$("#toast");e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2600)}
async function api(path,opt={}){const r=await fetch("https://api.github.com"+path,{...opt,headers:{Accept:"application/vnd.github+json",Authorization:"Bearer "+token,"X-GitHub-Api-Version":"2022-11-28",...(opt.headers||{})}});if(!r.ok){let j={};try{j=await r.json()}catch{}throw new Error(j.message||`GitHub error ${r.status}`)}return r.status===204?null:r.json()}
function dec(b){return decodeURIComponent(escape(atob(b.replace(/\n/g,""))))}
function enc(s){return btoa(unescape(encodeURIComponent(s)))}
async function getFile(path){try{const r=await api(`/repos/${REPO}/contents/${path}?ref=${BRANCH}`);sha[path]=r.sha;return JSON.parse(dec(r.content))}catch(e){if(e.message.includes("404")){sha[path]=null;return null}throw e}}
async function putJson(path,obj,msg){const body={message:msg||`Update ${path}`,content:enc(JSON.stringify(obj,null,2)+"\n"),branch:BRANCH};if(sha[path])body.sha=sha[path];const r=await api(`/repos/${REPO}/contents/${path}`,{method:"PUT",body:JSON.stringify(body)});sha[path]=r.content.sha;toast("Published ✓");return r}
async function delPath(path){const r=await api(`/repos/${REPO}/contents/${path}?ref=${BRANCH}`);await api(`/repos/${REPO}/contents/${path}`,{method:"DELETE",body:JSON.stringify({message:`Delete ${path}`,sha:r.sha,branch:BRANCH})})}
function showSection(id){$$(".section").forEach(x=>x.classList.toggle("active",x.id===id));$$("[data-section]").forEach(x=>x.classList.toggle("active",x.dataset.section===id));$("#pageTitle").textContent=id==="dashboard"?"Dashboard":id==="content"?"Content Studio":id[0].toUpperCase()+id.slice(1);if(id==="files")loadFiles()}
async function loadAll(){for(const [k,p] of Object.entries(FILES)){data[k]=await getFile(p);if(data[k]==null)data[k]=structuredClone(defaults[k])}renderAll();$("#statusText").textContent="Connected"}
function renderAll(){renderStats();renderProfile();["research","projects","library","content","timeline"].forEach(renderCollection);renderCategories()}
function renderStats(){const values=[["Research",data.research.length],["Projects",data.projects.length],["Published",data.content.length],["Categories",data.categories.length]];$("#stats").innerHTML=values.map(v=>`<div class="stat"><b>${v[1]}</b><span>${v[0]}</span></div>`).join("")}
function renderProfile(){const p=data.profile||{};const simple=["name","title","tagline","bio","summary","email","linkedin","github","university","department","degree","location","education","goals"];let h=simple.map(k=>`<div class="field"><label>${k}</label><textarea data-profile="${k}">${esc(p[k]||"")}</textarea></div>`).join("");h+=["focus","skills","labSkills","tools","principles"].map(k=>`<div class="field"><label>${k} <small>one item per line</small></label><textarea data-profile-array="${k}">${esc((p[k]||[]).join("\n"))}</textarea></div>`).join("");$("#profileEditor").innerHTML=h}
async function saveProfile(){const p={...data.profile};$$("[data-profile]").forEach(e=>p[e.dataset.profile]=e.value);$$("[data-profile-array]").forEach(e=>p[e.dataset.profileArray]=e.value.split("\n").map(x=>x.trim()).filter(Boolean));data.profile=p;await putJson("profile.json",p,"Update profile");renderProfile()}
function titleOf(x){return x.title||x.name||x.heading||x.role||"Untitled"}function descOf(x){return x.description||x.summary||x.excerpt||x.body||""}
function renderCollection(kind){const el=$("#"+kind+"List");if(!el)return;el.innerHTML=(data[kind]||[]).map((x,i)=>`<div class="card"><div><h4>${esc(titleOf(x))}</h4><p>${esc(descOf(x))}</p><div class="meta">${[x.category,x.type,x.year,x.date,x.featured?"FEATURED":""].filter(Boolean).map(t=>`<span>${esc(t)}</span>`).join("")}</div></div><div class="actions"><button class="small" onclick="editItem('${kind}',${i})">Edit</button><button class="small danger" onclick="removeItem('${kind}',${i})">Delete</button></div></div>`).join("")||`<div class="card"><p>No entries yet.</p></div>`}
function fieldsFor(kind,item){const map={research:["title","category","status","year","description","methods","keywords","link"],projects:["title","category","status","year","description","technologies","link"],library:["title","category","type","year","description","url","file"],timeline:["year","title","description","type"],content:["title","category","description","body","date","featured","media","type"]};return (map[kind]||[]).map(k=>{if(k==="featured")return`<label class="check"><input data-field="featured" type="checkbox" ${item[k]?"checked":""}> Featured</label>`;return`<div class="field"><label>${k}</label><textarea data-field="${k}">${esc(item[k]??"")}</textarea></div>`}).join("")}
function editItem(kind,i){const item=i==null?{}:data[kind][i];$("#dialogTitle").textContent=i==null?`Add ${kind.slice(0,-1)}`:`Edit ${kind.slice(0,-1)}`;$("#dialogBody").innerHTML=fieldsFor(kind,item);$("#dialogSave").onclick=async e=>{e.preventDefault();const obj={...item};$$("[data-field]").forEach(x=>obj[x.dataset.field]=x.type==="checkbox"?x.checked:x.value);if(i==null)data[kind].push(obj);else data[kind][i]=obj;await putJson(FILES[kind],data[kind],`Update ${kind}`);renderCollection(kind);$("#editorDialog").close()};$("#editorDialog").showModal()}
async function removeItem(kind,i){if(!confirm(`Delete "${titleOf(data[kind][i])}"?`))return;data[kind].splice(i,1);await putJson(FILES[kind],data[kind],`Delete ${kind} item`);renderCollection(kind)}
function renderCategories(){$("#categoryList").innerHTML=data.categories.map((x,i)=>`<div class="category"><span>${esc(x)}</span><button class="small danger" onclick="removeCategory(${i})">Delete</button></div>`).join("")}
async function addCategory(){const c=prompt("New category name");if(!c?.trim())return;data.categories.push(c.trim());await putJson("categories.json",data.categories,"Add category");renderCategories()}
async function removeCategory(i){if(!confirm(`Delete ${data.categories[i]}?`))return;data.categories.splice(i,1);await putJson("categories.json",data.categories,"Delete category");renderCategories()}
function folderFor(f){const t=(f.type||"").toLowerCase();if(t.startsWith("image/"))return"assets/images";if(t.startsWith("video/"))return"assets/videos";if(t.startsWith("audio/"))return"assets/audio";if(t.includes("pdf")||/\.pdf$/i.test(f.name))return"assets/documents";if(t.includes("presentation")||/\.pptx?$/i.test(f.name))return"assets/presentations";if(t.includes("word")||/\.docx?$/i.test(f.name))return"assets/documents";return"assets/files"}
async function uploadBinary(f){const buf=await f.arrayBuffer(),bytes=new Uint8Array(buf);let bin="";for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));const path=`${folderFor(f)}/${f.name}`;const body={message:`Upload ${f.name}`,content:btoa(bin),branch:BRANCH};try{const old=await api(`/repos/${REPO}/contents/${path}?ref=${BRANCH}`);body.sha=old.sha}catch{}await api(`/repos/${REPO}/contents/${path}`,{method:"PUT",body:JSON.stringify(body)});return path}
async function publishFileAsContent(f){const title=prompt("Title for this item",f.name.replace(/\.[^.]+$/,""));if(title===null)return;const description=prompt("Short description (what should appear on the website?)","");if(description===null)return;const category=prompt("Category",data.categories[0]||"Media")||"Media";const path=await uploadBinary(f);const ext=f.name.split(".").pop().toLowerCase();const type=f.type||({"jpg":"image","jpeg":"image","png":"image","webp":"image","gif":"image","mp4":"video","webm":"video","mp3":"audio","wav":"audio","pdf":"PDF","ppt":"PPT","pptx":"PPTX","doc":"DOC","docx":"DOCX"}[ext]||"FILE");data.content.unshift({title,description,body:"",category,type,date:new Date().toISOString().slice(0,10),featured:false,media:path});await putJson("content.json",data.content,"Publish media content");renderCollection("content")}
async function uploadFiles(files){for(const f of files){const row=document.createElement("div");row.className="queue-item";row.innerHTML=`<span>${esc(f.name)}</span><span>Preparing…</span>`;$("#uploadQueue").appendChild(row);try{row.lastChild.textContent="Uploading…";await publishFileAsContent(f);row.lastChild.textContent="Published ✓"}catch(e){row.lastChild.textContent="Failed: "+e.message}}toast("Upload workflow complete");loadFiles()}
async function loadFiles(){const box=$("#fileList");box.innerHTML="<div class='card'><p>Loading repository…</p></div>";try{const r=await api(`/repos/${REPO}/git/trees/${BRANCH}?recursive=1`);const fs=r.tree.filter(x=>x.type==="blob"&&!x.path.startsWith(".git/")).sort((a,b)=>a.path.localeCompare(b.path));box.innerHTML=fs.map(f=>`<div class="file-row"><div><b>${esc(f.path.split("/").pop())}</b><small>${esc(f.path)} • ${Math.round((f.size||0)/1024)} KB</small></div><button class="small danger" onclick="deleteRepoFile('${encodeURIComponent(f.path)}')">Delete</button></div>`).join("")}catch(e){box.innerHTML=`<div class="card"><p>${esc(e.message)}</p></div>`}}
async function deleteRepoFile(encPath){const path=decodeURIComponent(encPath);if(!confirm(`Delete ${path}?`))return;await delPath(path);toast("Deleted");loadFiles()}
function init(){const saved=sessionStorage.getItem("tab_github_token");if(saved){token=saved;connect().catch(()=>sessionStorage.removeItem("tab_github_token"))}$("#loginBtn").onclick=()=>{token=$("#tokenInput").value.trim();if(token)connect().catch(e=>toast(e.message))};$("#logoutBtn").onclick=()=>{sessionStorage.removeItem("tab_github_token");location.reload()};$("#refreshBtn").onclick=()=>loadAll().catch(e=>toast(e.message));$("#nav").onclick=e=>{const b=e.target.closest("button[data-section]");if(b)showSection(b.dataset.section)};$$(".quick-grid button").forEach(b=>b.onclick=()=>showSection(b.dataset.section));$("#saveProfile").onclick=saveProfile;$("#addCategory").onclick=addCategory;$("#newContent").onclick=()=>editItem("content",null);$$("[data-add]").forEach(b=>b.onclick=()=>editItem(b.dataset.add,null));$("#chooseFiles").onclick=()=>$("#fileInput").click();$("#fileInput").onchange=e=>uploadFiles(e.target.files);$("#refreshFiles").onclick=loadFiles;const dz=$("#dropZone");["dragenter","dragover"].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add("drag")}));["dragleave","drop"].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.remove("drag")}));dz.addEventListener("drop",e=>uploadFiles(e.dataTransfer.files))}
async function connect(){const u=await api("/user");if(u.login!=="BijranTahir")throw new Error("This admin is restricted to the GitHub account BijranTahir.");const r=await api(`/repos/${REPO}`);if(!r.permissions?.push)throw new Error("This token does not have write access to the website repository.");sessionStorage.setItem("tab_github_token",token);$("#loginView").classList.add("hidden");$("#appView").classList.remove("hidden");await loadAll()}
init();