const REPO="BijranTahir/BijranTahir.github.io", BRANCH="main";
const DATA_FILES={profile:"profile.json",research:"research.json",projects:"projects.json",library:"library.json",timeline:"timeline.json",categories:"categories.json"};
const DEFAULTS={
 profile:{name:"Tahir Ahmad Bijran",title:"Biotechnology • Research • Computational Biology",bio:"",email:"",linkedin:"",github:"BijranTahir",university:"Central University of Kashmir",department:"Biotechnology"},
 research:[],projects:[],library:[],timeline:[],categories:["Research","Projects","Publications","Certificates","Presentations","Documents","Notes"]
};
let token="", data={}, sha={};

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2400)}
function esc(v=""){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function api(path,opt={}){const r=await fetch("https://api.github.com"+path,{...opt,headers:{Accept:"application/vnd.github+json",Authorization:"Bearer "+token,"X-GitHub-Api-Version":"2022-11-28",...(opt.headers||{})}});if(!r.ok){let j={};try{j=await r.json()}catch{};throw new Error(j.message||`GitHub error ${r.status}`)}return r.status===204?null:r.json()}
async function getFile(path){try{const r=await api(`/repos/${REPO}/contents/${path}?ref=${BRANCH}`);sha[path]=r.sha;return JSON.parse(decodeURIComponent(escape(atob(r.content.replace(/\n/g,"")))))}catch(e){if(e.message.includes("404")){sha[path]=null;return null}throw e}}
function encodeUtf8(s){return btoa(unescape(encodeURIComponent(s)))}
async function putFile(path,obj,msg){const content=encodeUtf8(JSON.stringify(obj,null,2)+"\n");const body={message:msg||`Update ${path}`,content,branch:BRANCH};if(sha[path])body.sha=sha[path];const r=await api(`/repos/${REPO}/contents/${path}`,{method:"PUT",body:JSON.stringify(body)});sha[path]=r.content.sha;toast(`Saved ${path}`);return r}
async function delFile(path){await api(`/repos/${REPO}/contents/${path}`,{method:"DELETE",body:JSON.stringify({message:`Delete ${path}`,sha:sha[path],branch:BRANCH})});toast("Deleted");}

function showSection(id){$$(".section").forEach(x=>x.classList.toggle("active",x.id===id));$$("#nav button").forEach(x=>x.classList.toggle("active",x.dataset.section===id));$("#pageTitle").textContent=id==="dashboard"?"Dashboard":id[0].toUpperCase()+id.slice(1);if(id==="files")loadFiles()}
async function loadAll(){for(const [k,p] of Object.entries(DATA_FILES)){let v=await getFile(p);data[k]=v??structuredClone(DEFAULTS[k])}renderAll();$("#statusText").textContent="Connected";toast("Content refreshed")}
function renderAll(){renderStats();renderProfile();renderCollection("research");renderCollection("projects");renderCollection("library");renderCollection("timeline");renderCategories()}
function renderStats(){$("#stats").innerHTML=[["research",data.research.length],["projects",data.projects.length],["library",data.library.length],["categories",data.categories.length]].map(x=>`<div class="stat"><b>${x[1]}</b><span>${x[0]}</span></div>`).join("")}
function renderProfile(){const p=data.profile||{};$("#profileEditor").innerHTML=Object.entries(p).map(([k,v])=>`<div class="field"><label>${esc(k)}</label><textarea data-profile="${esc(k)}">${esc(v)}</textarea></div>`).join("")}
function saveProfile(){document.querySelectorAll("[data-profile]").forEach(x=>data.profile[x.dataset.profile]=x.value);return putFile("profile.json",data.profile,"Update profile")}
function itemTitle(x){return x.title||x.name||x.heading||x.role||"Untitled"}
function itemDesc(x){return x.description||x.summary||x.excerpt||x.type||""}
function renderCollection(kind){const el=$("#"+kind+"List");el.innerHTML=(data[kind]||[]).map((x,i)=>`<div class="card"><div><h4>${esc(itemTitle(x))}</h4><p>${esc(itemDesc(x))}</p><div class="card-meta">${[x.category,x.status,x.year,x.type].filter(Boolean).map(t=>`<span class="tag">${esc(t)}</span>`).join("")}</div></div><div class="card-actions"><button class="small-btn" onclick="editItem('${kind}',${i})">Edit</button><button class="small-btn danger" onclick="removeItem('${kind}',${i})">Delete</button></div></div>`).join("")||`<div class="card"><p>No entries yet.</p></div>`}
function renderCategories(){$("#categoryList").innerHTML=data.categories.map((c,i)=>`<div class="category"><span>${esc(c)}</span><button class="small-btn danger" onclick="removeCategory(${i})">Delete</button></div>`).join("")}
function fieldsFor(kind,item){const base=kind==="research"?["title","category","status","year","description","methods","keywords","link"]:kind==="projects"?["title","category","status","year","description","technologies","link"]:kind==="library"?["title","category","type","year","description","url","file"]:["date","title","description","type"];return base.map(k=>`<div class="field"><label>${k}</label><textarea data-field="${k}">${esc(item[k]??"")}</textarea></div>`).join("")}
function editItem(kind,i){const item=i==null?{}:data[kind][i];$("#dialogTitle").textContent=i==null?`Add ${kind.slice(0,-1)}`:`Edit ${kind.slice(0,-1)}`;$("#dialogBody").innerHTML=fieldsFor(kind,item);$("#dialogSave").onclick=async e=>{e.preventDefault();const obj={...item};$$("[data-field]").forEach(x=>obj[x.dataset.field]=x.value);if(i==null)data[kind].push(obj);else data[kind][i]=obj;await putFile(DATA_FILES[kind],data[kind],`Update ${kind}`);renderCollection(kind);$("#editorDialog").close()};$("#editorDialog").showModal()}
async function removeItem(kind,i){if(!confirm(`Delete "${itemTitle(data[kind][i])}"?`))return;data[kind].splice(i,1);await putFile(DATA_FILES[kind],data[kind],`Delete ${kind} item`);renderCollection(kind)}
function addCategory(){const c=prompt("Category name");if(c&&c.trim()){data.categories.push(c.trim());putFile("categories.json",data.categories,"Add category").then(renderCategories)}}
async function removeCategory(i){if(!confirm(`Delete category "${data.categories[i]}"?`))return;data.categories.splice(i,1);await putFile("categories.json",data.categories,"Delete category");renderCategories()}
async function loadFiles(){const box=$("#fileList");box.innerHTML="<div class='card'><p>Loading repository files…</p></div>";try{const r=await api(`/repos/${REPO}/git/trees/${BRANCH}?recursive=1`);const files=r.tree.filter(x=>x.type==="blob"&&!x.path.startsWith(".git/")).sort((a,b)=>a.path.localeCompare(b.path));box.innerHTML=files.map(f=>`<div class="file-row"><div><div class="file-name">${esc(f.path.split("/").pop())}</div><div class="file-path">${esc(f.path)} • ${Math.round((f.size||0)/1024)} KB</div></div><div class="card-actions"><button class="small-btn danger" onclick="deleteRepoFile('${encodeURIComponent(f.path)}')">Delete</button></div></div>`).join("")}catch(e){box.innerHTML=`<div class="card"><p>${esc(e.message)}</p></div>`}}
async function deleteRepoFile(enc){const path=decodeURIComponent(enc);if(!confirm(`Delete ${path}?`))return;const r=await api(`/repos/${REPO}/contents/${path}?ref=${BRANCH}`);await api(`/repos/${REPO}/contents/${path}`,{method:"DELETE",body:JSON.stringify({message:`Delete ${path}`,sha:r.sha,branch:BRANCH})});toast("File deleted");loadFiles()}
async function uploadFiles(files){const q=$("#uploadQueue");for(const f of files){const row=document.createElement("div");row.className="queue-item";row.innerHTML=`<span>${esc(f.name)}</span><span>Uploading…</span>`;q.appendChild(row);try{const buf=await f.arrayBuffer();let binary="";const bytes=new Uint8Array(buf);const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,i+chunk));const b64=btoa(binary);const folder=f.type.startsWith("image/")?"assets/images":f.type.startsWith("video/")?"assets/videos":f.type.includes("pdf")?"assets/documents":f.type.includes("presentation")||/\.pptx?$/.test(f.name)?"assets/presentations":f.type.includes("word")||/\.docx?$/.test(f.name)?"assets/documents":"assets/files";const path=`${folder}/${f.name}`;const body={message:`Upload ${f.name}`,content:b64,branch:BRANCH};try{const old=await api(`/repos/${REPO}/contents/${path}?ref=${BRANCH}`);body.sha=old.sha}catch{}await api(`/repos/${REPO}/contents/${path}`,{method:"PUT",body:JSON.stringify(body)});row.lastElementChild.textContent="Done ✓"}catch(e){row.lastElementChild.textContent="Failed: "+e.message}}toast("Upload finished");loadFiles()}
function init(){const saved=sessionStorage.getItem("tab_github_token");if(saved){token=saved;connect().catch(()=>sessionStorage.removeItem("tab_github_token"))}$("#loginBtn").onclick=()=>{token=$("#tokenInput").value.trim();if(!token)return;connect().catch(e=>toast(e.message))};$("#logoutBtn").onclick=()=>{sessionStorage.removeItem("tab_github_token");location.reload()};$("#refreshBtn").onclick=()=>loadAll().catch(e=>toast(e.message));$("#nav").onclick=e=>{const b=e.target.closest("button[data-section]");if(b)showSection(b.dataset.section)};$$("[data-section]").forEach(b=>b.onclick=()=>showSection(b.dataset.section));$("#addCategoryBtn").onclick=addCategory;$("#chooseFiles").onclick=()=>$("#fileInput").click();$("#fileInput").onchange=e=>uploadFiles(e.target.files);$("#refreshFiles").onclick=loadFiles;const dz=$("#dropZone");["dragenter","dragover"].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.style.borderColor="#207e70"}));["dragleave","drop"].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.style.borderColor="#b9d2ce"}));dz.addEventListener("drop",e=>uploadFiles(e.dataTransfer.files));$$("[data-save-json]").forEach(b=>b.onclick=()=>saveProfile());$$("[data-add]").forEach(b=>b.onclick=()=>editItem(b.dataset.add));}
async function connect(){const u=await api("/user");if(u.login!=="BijranTahir")throw new Error("This admin is restricted to the GitHub account BijranTahir.");const r=await api(`/repos/${REPO}`);if(!r.permissions?.push)throw new Error("This token does not have write access to the website repository.");sessionStorage.setItem("tab_github_token",token);$("#loginView").classList.add("hidden");$("#appView").classList.remove("hidden");await loadAll()}
init();
