(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)]; const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); const key=k=>'scientificWorkspace:'+k; const read=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(key(k)))??d}catch{return d}}; const write=(k,v)=>localStorage.setItem(key(k),JSON.stringify(v)); const toast=m=>{let t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2200)};
const data={profile:{},research:[],projects:[],library:[],timeline:[],content:[],protocols:[],publications:[],experiments:[],labnotes:[]};
async function get(f,d){try{const r=await fetch(f,{cache:'no-store'});if(!r.ok)throw 0;return await r.json()}catch{return d}}
async function init(){[data.profile,data.research,data.projects,data.library,data.timeline,data.content,data.protocols,data.publications,data.experiments,data.labnotes]=await Promise.all([get('profile.json',{}),get('research.json',[]),get('projects.json',[]),get('library.json',[]),get('timeline.json',[]),get('content.json',[]),get('protocols.json',[]),get('publications.json',[]),get('experiments.json',[]),get('labnotes.json',[])]);renderAll();bind();}
const navItems=[['home','Home'],['about','Profile'],['dashboard','Command Center'],['research','Research'],['ideas','Research Ideas'],['expertise','Expertise'],['biotools','BioTools'],['data','Data Studio'],['experiments','Experiments'],['notebook','Lab Notebook'],['protocols','Protocols'],['literature','Literature'],['publications','Publications'],['calculators','Calculators'],['workflow','Computational Biology'],['microscopy','Microscopy'],['projects','Projects'],['library','Library'],['visualization','Visualization Studio'],['skills','Evidence & Skills'],['inventory','Lab Inventory'],['journal','Scientific Journal'],['knowledge','Knowledge Graph'],['analytics','Analytics'],['cv','Academic CV'],['docs','Documentation'],['changelog','Changelog'],['journey','Journey'],['collaborate','Collaborate'],['contact','Contact']];
function renderNav(){$('#nav').innerHTML=navItems.map((x,i)=>`<a href="#${x[0]}"><span>${String(i+1).padStart(2,'0')}</span>${x[1]}</a>`).join('')}
function renderAll(){renderNav();const p=data.profile||{};$('#heroBio').textContent=p.bio||p.tagline||$('#heroBio').textContent;$('#degree').textContent=p.degree||'B.Sc. (Hons) Biotechnology';$('#aboutSummary').textContent=p.summary||'';$('#aboutBio').textContent=p.goals||p.bio||'';$('#facts').innerHTML=[['Degree',p.degree],['University',p.university],['Department',p.department],['Location',p.location]].map(x=>`<div><small>${esc(x[0])}</small><b>${esc(x[1]||'')}</b></div>`).join('');renderResearch();renderDashboard();renderExpertise();renderProjects();renderLibrary();renderProtocols();renderPapers();renderPubs();renderTimeline();renderCV();renderNotes();renderExperiments();renderIdeas();renderInventory();renderJournal();renderSkills();renderKnowledge();renderAnalytics();renderChangelog();}
function renderResearch(){let e=$('#researchGrid');e.innerHTML=data.research.length?data.research.map((x,i)=>`<article class="card"><small>${String(i+1).padStart(2,'0')} / ${esc(x.status||'RESEARCH')}</small><h3>${esc(x.title)}</h3><p>${esc(x.description||'')}</p><div class="progress"><i style="width:${Math.max(0,Math.min(100,Number(x.progress||0)))}%"></i></div><b class="pct">${Number(x.progress||0)}%</b></article>`).join(''):'<div class="empty">No research entries yet.</div>'}
function renderDashboard(){const local=[['Ideas',read('ideas').length],['Experiments',read('experiments').length+data.experiments.length],['Notes',read('notes').length+data.labnotes.length],['Journal',read('journal').length],['Inventory',read('inventory').length]];const stats=[['Research areas',data.research.length],['Projects',data.projects.length],['Publications',data.publications.length],['Protocols',data.protocols.length],...local];$('#metrics').innerHTML=stats.map(x=>`<div class="metric"><b>${x[1]}</b><span>${esc(x[0])}</span></div>`).join('');$('#progress').innerHTML=data.research.map(x=>{let n=Math.max(0,Math.min(100,Number(x.progress||0)));return `<div class="p-row"><div><b>${esc(x.title)}</b><span>${n}%</span></div><div class="progress"><i style="width:${n}%"></i></div></div>`}).join('');const acts=[...data.timeline].slice(-6).reverse();$('#activity').innerHTML=acts.length?acts.map(x=>`<div class="activity"><b>${esc(x.year||x.date||'')}</b><span>${esc(x.title||x.event||'Milestone')}</span></div>`).join(''):'<div class="empty">Add timeline entries through Admin.</div>'}
function renderExpertise(){let p=data.profile||{}, arr=p.focus||p.skills||[];$('#expertiseGrid').innerHTML=arr.map((x,i)=>`<article class="card"><small>${String(i+1).padStart(2,'0')}</small><h3>${esc(x)}</h3><p>${esc((p.skills||[])[i%(Math.max(1,(p.skills||[]).length))]||'Interdisciplinary scientific practice.')}</p></article>`).join('');$('#skillCloud').innerHTML=[...(p.labSkills||[]),...(p.tools||[])].map(x=>`<span>${esc(x)}</span>`).join('')}
function renderProjects(){let e=$('#projectGrid');e.innerHTML=data.projects.map(x=>`<article class="card"><small>${esc(x.category||x.type||'PROJECT')}</small><h3>${esc(x.title)}</h3><p>${esc(x.description||'')}</p><a class="text-link" href="${esc(x.url||x.link||'#')}" ${x.url||x.link?'target="_blank" rel="noopener"':''}>Open ↗</a></article>`).join('')||'<div class="empty">No projects yet.</div>'}
function renderLibrary(){let q=($('#librarySearch')?.value||'').toLowerCase();$('#libraryGrid').innerHTML=data.library.filter(x=>(`${x.title||''} ${x.description||''} ${x.type||''} ${x.category||''}`).toLowerCase().includes(q)).map(x=>`<article class="card"><small>${esc(x.type||x.category||'RESOURCE')}</small><h3>${esc(x.title)}</h3><p>${esc(x.description||'')}</p>${x.file||x.url?`<a class="text-link" href="${esc(x.file||x.url)}" target="_blank" rel="noopener">Open ↗</a>`:''}</article>`).join('')||'<div class="empty">No library items match.</div>'}
function renderProtocols(){$('#protocolGrid').innerHTML=data.protocols.map(x=>`<article class="card"><small>PROTOCOL</small><h3>${esc(x.title)}</h3><p>${esc(x.purpose||x.description||'')}</p><details><summary>View details</summary><p>${esc(x.steps||x.method||'')}</p></details></article>`).join('')||'<div class="empty">No protocols yet.</div>'}
function renderPapers(){let q=($('#paperSearch')?.value||'').toLowerCase();$('#paperGrid').innerHTML=data.publications.filter(x=>(`${x.title||''} ${x.authors||''} ${x.journal||''} ${x.keywords||''}`).toLowerCase().includes(q)).map(x=>`<article class="card"><small>${esc(x.year||'PAPER')} · ${esc(x.journal||'')}</small><h3>${esc(x.title)}</h3><p>${esc(x.authors||x.abstract||'')}</p>${x.doi?`<a class="text-link" href="https://doi.org/${encodeURIComponent(x.doi)}" target="_blank" rel="noopener">DOI ↗</a>`:''}</article>`).join('')||'<div class="empty">No papers match.</div>'}
function renderPubs(){$('#pubGrid').innerHTML=data.publications.map(x=>`<article class="card"><small>${esc(x.year||'PUBLICATION')}</small><h3>${esc(x.title)}</h3><p>${esc(x.abstract||x.description||x.authors||'')}</p></article>`).join('')||'<div class="empty">Publications added through Admin will appear here.</div>'}
function renderTimeline(){$('#timeline').innerHTML=data.timeline.map(x=>`<div class="timeline-item"><b>${esc(x.year||x.date||'')}</b><div><h3>${esc(x.title||x.event||'')}</h3><p>${esc(x.description||x.text||'')}</p></div></div>`).join('')}
function renderCV(){const p=data.profile||{};$('#cvBody').innerHTML=`<div class="cv"><h2>${esc(p.name||'Tahir Ahmad Bijran')}</h2><p>${esc(p.title||'Biotechnology • Research • Computational Biology')}</p><hr><h3>Profile</h3><p>${esc(p.bio||p.summary||'')}</p><h3>Education</h3><p>${esc(p.degree||'B.Sc. (Hons) Biotechnology')} — ${esc(p.university||'Central University of Kashmir')}</p><h3>Focus</h3><p>${esc((p.focus||[]).join(' • '))}</p><h3>Skills</h3><p>${esc((p.skills||[]).join(' • '))}</p></div>`}
function renderNotes(){const all=[...data.labnotes,...read('notes')];$('#notesList').innerHTML=all.slice().reverse().map((x,i)=>`<article class="list-item"><div><small>${esc(x.date||'')}</small><h3>${esc(x.title||'Untitled')}</h3><p>${esc(x.body||x.content||'')}</p></div></article>`).join('')||'<div class="empty">No notes yet.</div>'}
function renderExperiments(){const all=[...data.experiments,...read('experiments')];$('#expList').innerHTML=all.slice().reverse().map(x=>`<article class="list-item"><div><small>${esc(x.status||'Experiment')} · ${esc(x.date||x.created||'')}</small><h3>${esc(x.title||'Untitled')}</h3><p>${esc(x.objective||'')}</p></div></article>`).join('')||'<div class="empty">No experiments yet.</div>'}
function renderIdeas(){let xs=read('ideas');$('#ideasList').innerHTML=xs.slice().reverse().map((x,i)=>`<article class="list-item"><div><small>${esc(x.status)}</small><h3>${esc(x.title)}</h3><p><b>Gap:</b> ${esc(x.gap)}</p><p><b>Hypothesis:</b> ${esc(x.hypothesis)}</p><p>${esc(x.method)}</p></div><button class="mini danger" data-del-idea="${xs.length-1-i}">Delete</button></article>`).join('')||'<div class="empty">No local research ideas yet.</div>'}
function renderInventory(){let xs=read('inventory');$('#invList').innerHTML=xs.slice().reverse().map((x,i)=>`<article class="list-item"><div><small>${esc(x.category)} · ${esc(x.status)}</small><h3>${esc(x.item)}</h3><p>${esc(x.notes)}</p></div><button class="mini danger" data-del-inv="${xs.length-1-i}">Delete</button></article>`).join('')||'<div class="empty">No local inventory items.</div>'}
function renderJournal(){let xs=read('journal');$('#journalList').innerHTML=xs.slice().reverse().map((x,i)=>`<article class="list-item"><div><small>${esc(x.date)} · ${esc(x.type)}</small><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p></div><button class="mini danger" data-del-j="${xs.length-1-i}">Delete</button></article>`).join('')||'<div class="empty">No journal entries yet.</div>'}
function renderSkills(){let p=data.profile||{}, arr=[...(p.skills||[]),...(p.labSkills||[])];$('#skillsGrid').innerHTML=arr.map((x,i)=>`<article class="card"><small>SKILL ${String(i+1).padStart(2,'0')}</small><h3>${esc(x)}</h3><p>Learn → Practice → Document → Evidence</p></article>`).join('')}
function renderKnowledge(){const nodes=['Molecular Biology','Nanobiotechnology','Bioinformatics','Microbiology','Data Analysis','Scientific Visualization','Literature','Experiments','Scientific Communication'];$('#knowledgeGraph').innerHTML=nodes.map((x,i)=>`<button class="knowledge-node" style="--i:${i}" data-node="${esc(x)}">${esc(x)}</button>`).join('')}
function renderAnalytics(){const stats=[['Local ideas',read('ideas').length],['Local experiments',read('experiments').length],['Local notes',read('notes').length],['Local journal',read('journal').length],['Local inventory',read('inventory').length],['Public research areas',data.research.length]];$('#analyticsStats').innerHTML=stats.map(x=>`<div class="stat-line"><span>${esc(x[0])}</span><b>${x[1]}</b></div>`).join('');$('#activityChart').innerHTML=stats.map((x,i)=>`<div class="bar"><span>${esc(x[0])}</span><i style="height:${Math.min(100,10+x[1]*12)}%"></i><b>${x[1]}</b></div>`).join('')}
function renderChangelog(){const rows=[['2026','Scientific Workspace architecture'],['2026','Dark-only interface and mobile navigation'],['2026','BioTools and Data Studio'],['2026','Digital laboratory and research workspace']];$('#changeList').innerHTML=rows.map(x=>`<div class="timeline-item"><b>${x[0]}</b><div><h3>${x[1]}</h3><p>Workspace milestone.</p></div></div>`).join('')}
function bind(){
$('#year').textContent=new Date().getFullYear();
$('#menuBtn').onclick=()=>openDrawer();$('#drawerClose').onclick=closeDrawer;$('#drawerBack').onclick=closeDrawer;$('#nav').onclick=e=>{if(e.target.closest('a'))closeDrawer()};function openDrawer(){$('#drawer').classList.add('open');$('#drawer').setAttribute('aria-hidden','false');document.body.classList.add('locked')}function closeDrawer(){$('#drawer').classList.remove('open');$('#drawer').setAttribute('aria-hidden','true');document.body.classList.remove('locked')}
$('#searchBtn').onclick=()=>{$('#command').classList.add('open');$('#command').setAttribute('aria-hidden','false');setTimeout(()=>$('#globalSearch').focus(),50)};$('#commandClose').onclick=closeCommand;$('.modal-back').onclick=closeCommand;function closeCommand(){$('#command').classList.remove('open');$('#command').setAttribute('aria-hidden','true')}
const searchable=()=>[...navItems.map(x=>({title:x[1],type:'Section',href:'#'+x[0]})),...data.research.map(x=>({title:x.title,type:'Research',href:'#research'})),...data.projects.map(x=>({title:x.title,type:'Project',href:'#projects'})),...data.publications.map(x=>({title:x.title,type:'Publication',href:'#publications'}))];$('#globalSearch').oninput=e=>{let q=e.target.value.toLowerCase().trim();let arr=searchable().filter(x=>(x.title+' '+x.type).toLowerCase().includes(q)).slice(0,30);$('#searchResults').innerHTML=arr.map(x=>`<a href="${x.href}" data-command-link><small>${esc(x.type)}</small><b>${esc(x.title)}</b></a>`).join('')||'<div class="empty">No matches.</div>'};$('#searchResults').onclick=e=>{if(e.target.closest('[data-command-link]'))closeCommand()};
$('#librarySearch').oninput=renderLibrary;$('#paperSearch').oninput=renderPapers;
$('#ideaForm').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.date=new Date().toISOString().slice(0,10);let a=read('ideas');a.push(o);write('ideas',a);e.target.reset();renderIdeas();renderDashboard();renderAnalytics();toast('Research idea saved locally.')};document.addEventListener('click',e=>{let b=e.target.closest('[data-del-idea]');if(b){let a=read('ideas');a.splice(+b.dataset.delIdea,1);write('ideas',a);renderIdeas();renderDashboard();renderAnalytics()}b=e.target.closest('[data-del-inv]');if(b){let a=read('inventory');a.splice(+b.dataset.delInv,1);write('inventory',a);renderInventory();renderDashboard();renderAnalytics()}b=e.target.closest('[data-del-j]');if(b){let a=read('journal');a.splice(+b.dataset.delJ,1);write('journal',a);renderJournal();renderDashboard();renderAnalytics()}});
$('#noteForm').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));let a=read('notes');a.push(o);write('notes',a);e.target.reset();renderNotes();renderDashboard();renderAnalytics();toast('Notebook entry saved locally.')};$('#expForm').onsubmit=e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));o.created=new Date().toISOString();let a=read('experiments');a.push(o);write('experiments',a);e.target.reset();renderExperiments();renderDashboard();renderAnalytics();toast('Experiment saved locally.')};$('#exportExp').onclick=()=>{let f=$('#expForm'),o=Object.fromEntries(new FormData(f));download('experiment.txt',Object.entries(o).map(([k,v])=>k.toUpperCase()+':\n'+v).join('\n\n'))};
$('#invForm').onsubmit=e=>{e.preventDefault();let a=read('inventory');a.push(Object.fromEntries(new FormData(e.target)));write('inventory',a);e.target.reset();renderInventory();renderDashboard();renderAnalytics();toast('Inventory item saved locally.')};$('#journalForm').onsubmit=e=>{e.preventDefault();let a=read('journal');a.push(Object.fromEntries(new FormData(e.target)));write('journal',a);e.target.reset();renderJournal();renderDashboard();renderAnalytics();toast('Journal entry saved locally.')};
$$('[data-calc]').forEach(b=>b.onclick=()=>calc(b.dataset.calc));$('#printCV').onclick=()=>window.print();
$('#loadSample').onclick=()=>{$('#dataInput').value='Time,OD600\n0,0.10\n1,0.14\n2,0.21\n3,0.31\n4,0.46\n5,0.68';parseData()};$('#csvFile').onchange=e=>{let f=e.target.files[0];if(f){let r=new FileReader();r.onload=()=>{$('#dataInput').value=r.result;parseData()};r.readAsText(f)}};$('#analyzeData').onclick=parseData;$('#plotData').onclick=plotData;$('#clearData').onclick=()=>{$('#dataInput').value='';$('#dataStats').innerHTML='';$('#chart').getContext('2d').clearRect(0,0,$('#chart').width,$('#chart').height)};$('#exportCSV').onclick=()=>download('dataset.csv',$('#dataInput').value,'text/csv');$('#savePNG').onclick=()=>{let a=document.createElement('a');a.download='scientific-plot.png';a.href=$('#chart').toDataURL('image/png');a.click()};
$$('#bioTabs button').forEach(b=>b.onclick=()=>{$$('#bioTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');b.dataset.tool});$('#analyzeSeq').onclick=analyzeSequence;$('#clearSeq').onclick=()=>{$('#sequenceInput').value='';$('#bioResult').innerHTML=''};$('#copySeq').onclick=async()=>{try{await navigator.clipboard.writeText($('#bioResult').innerText);toast('Result copied.')}catch{toast('Copy unavailable in this browser.')}};
$('#addNode').onclick=()=>{let n=prompt('Workflow stage name');if(n){let a=read('workflow',['Input','Quality Control','Processing','Analysis','Visualization','Interpretation','Output']);a.push(n);write('workflow',a);renderWorkflow()}};$('#resetWorkflow').onclick=()=>{write('workflow',['Input','Quality Control','Processing','Analysis','Visualization','Interpretation','Output']);renderWorkflow()};$('#saveWorkflow').onclick=()=>{download('workflow.json',JSON.stringify(read('workflow',['Input']),null,2),'application/json')};renderWorkflow();
$('#addViz').onclick=()=>{let n=prompt('Figure node');if(n){let d=$('#vizBoard'),el=document.createElement('div');el.className='viz-node';el.textContent=n;d.append(el)}};$('#clearViz').onclick=()=>{$('#vizBoard').innerHTML='<div class="viz-node">Question</div><div class="arrow">→</div><div class="viz-node">Method</div><div class="arrow">→</div><div class="viz-node">Data</div><div class="arrow">→</div><div class="viz-node">Analysis</div><div class="arrow">→</div><div class="viz-node">Conclusion</div>'};$('#saveViz').onclick=()=>{write('viz',$('#vizBoard').innerText);toast('Figure layout saved locally.')};
$('#microFiles').onchange=e=>loadMicro(e.target.files);$('#microDrop').onclick=()=>$('#microFiles').click();$('#microDrop').ondragover=e=>{e.preventDefault();$('#microDrop').classList.add('drag')};$('#microDrop').ondragleave=()=>$('#microDrop').classList.remove('drag');$('#microDrop').ondrop=e=>{e.preventDefault();$('#microDrop').classList.remove('drag');loadMicro(e.dataTransfer.files)};
$$('.mini[data-action="refresh"]').forEach(x=>x.onclick=renderAll);window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchBtn').click()}if(e.key==='Escape'){closeCommand();closeDrawer()}});
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw-v10.js').catch(()=>{});}
function analyzeSequence(){let raw=$('#sequenceInput').value.replace(/^>.*$/gm,'').replace(/\s/g,'').toUpperCase();if(!raw){$('#bioResult').innerHTML='<div class="empty">Enter a sequence.</div>';return}let dna=/^[ACGTUNRYKMSWBDHV]+$/.test(raw),gc=(raw.match(/[GC]/g)||[]).length,at=(raw.match(/[AT]/g)||[]).length;let rc=raw.split('').reverse().map(c=>({A:'T',T:'A',G:'C',C:'G',U:'A'}[c]||'N')).join('');let comp=(raw.match(/[ACGT]/g)||[]).length;let mass=dna?comp*308.0:raw.length*110.0;let codons=dna?translate(raw.replace(/U/g,'T')):'';$('#bioResult').innerHTML=`<div class="result-grid"><div><small>Length</small><b>${raw.length}</b></div><div><small>GC%</small><b>${((gc/Math.max(1,raw.length))*100).toFixed(2)}%</b></div><div><small>Estimated mass</small><b>${mass.toFixed(0)} Da</b></div><div><small>Type</small><b>${dna?'Nucleic acid':'Protein / unknown'}</b></div></div>${dna?`<h4>Reverse complement</h4><code>${rc}</code><h4>Frame +1 translation</h4><code>${codons}</code>`:''}`}
function translate(s){const t={TTT:'F',TTC:'F',TTA:'L',TTG:'L',TCT:'S',TCC:'S',TCA:'S',TCG:'S',TAT:'Y',TAC:'Y',TAA:'*',TAG:'*',TGT:'C',TGC:'C',TGA:'*',TGG:'W',CTT:'L',CTC:'L',CTA:'L',CTG:'L',CCT:'P',CCC:'P',CCA:'P',CCG:'P',CAT:'H',CAC:'H',CAA:'Q',CAG:'Q',CGT:'R',CGC:'R',CGA:'R',CGG:'R',ATT:'I',ATC:'I',ATA:'I',ATG:'M',ACT:'T',ACC:'T',ACA:'T',ACG:'T',AAT:'N',AAC:'N',AAA:'K',AAG:'K',AGT:'S',AGC:'S',AGA:'R',AGG:'R',GTT:'V',GTC:'V',GTA:'V',GTG:'V',GCT:'A',GCC:'A',GCA:'A',GCG:'A',GAT:'D',GAC:'D',GAA:'E',GAG:'E',GGT:'G',GGC:'G',GGA:'G',GGG:'G'};let o='';for(let i=0;i+2<s.length;i+=3)o+=t[s.slice(i,i+3)]||'X';return o}
function calc(t){let v=(id)=>parseFloat($('#'+id).value);let out,msg;if(t==='dilution')out=v('c1')&&v('c2')?`V1 = ${(v('c2')*v('v2')/v('c1')).toFixed(4)} (same volume unit)`:'';if(t==='molarity')out=v('lit')?`M = ${(v('mol')/v('lit')).toFixed(4)} mol/L`:'';if(t==='rcf')out=v('rpm')&&v('radius')?`RCF ≈ ${(1.118e-5*v('radius')*v('rpm')**2).toFixed(0)} × g`:'';if(t==='beer')out=v('epsilon')&&v('path')?`c = ${(v('absorb')/(v('epsilon')*v('path'))).toExponential(4)}`:'';if(t==='growth')out=v('n0')&&v('nt')&&v('nt')>v('n0')?`Doubling time ≈ ${(v('gt')*Math.log(2)/Math.log(v('nt')/v('n0'))).toFixed(4)} time units`:'';if(t==='cfu')out=v('vol')?`CFU/mL = ${(v('colonies')*v('dilution')/v('vol')).toExponential(4)}`:'';let map={dilution:'#o1',molarity:'#o2',rcf:'#o3',beer:'#o4',growth:'#o5',cfu:'#o6'};$(map[t]).textContent=out||'Check inputs.'}
function parseData(){let txt=$('#dataInput').value.trim();if(!txt)return;let rows=txt.split(/\r?\n/).map(r=>r.split(/\t|,/));let head=rows.shift();let nums=head.map((_,i)=>rows.map(r=>parseFloat(r[i])).filter(Number.isFinite));$('#xCol').innerHTML=head.map((h,i)=>`<option value="${i}">${esc(h)}</option>`).join('');$('#yCol').innerHTML=head.map((h,i)=>`<option value="${i}">${esc(h)}</option>`).join('');if(head.length>1)$('#yCol').value='1';let vals=nums.flatMap(a=>a);let mean=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0;$('#dataStats').innerHTML=`<div class="result-grid"><div><small>Rows</small><b>${rows.length}</b></div><div><small>Columns</small><b>${head.length}</b></div><div><small>Numeric values</small><b>${vals.length}</b></div><div><small>Mean</small><b>${mean.toFixed(4)}</b></div></div>`;plotData()}
function plotData(){let txt=$('#dataInput').value.trim();if(!txt)return;let rows=txt.split(/\r?\n/).map(r=>r.split(/\t|,/));let h=rows.shift();let xi=+$('#xCol').value||0,yi=+$('#yCol').value||1;let pts=rows.map(r=>[parseFloat(r[xi]),parseFloat(r[yi])]).filter(p=>p.every(Number.isFinite));let c=$('#chart'),ctx=c.getContext('2d'),w=c.width=c.clientWidth*devicePixelRatio,hgt=c.height=280*devicePixelRatio;ctx.clearRect(0,0,w,hgt);if(!pts.length)return;let minx=Math.min(...pts.map(p=>p[0])),maxx=Math.max(...pts.map(p=>p[0])),miny=Math.min(...pts.map(p=>p[1])),maxy=Math.max(...pts.map(p=>p[1]));let sx=x=>40+(x-minx)/Math.max(1,maxx-minx)*(w/devicePixelRatio-60),sy=y=>hgt/devicePixelRatio-35-(y-miny)/Math.max(1,maxy-miny)*(hgt/devicePixelRatio-55);ctx.strokeStyle='#23453d';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(40,10);ctx.lineTo(40,hgt/devicePixelRatio-35);ctx.lineTo(w/devicePixelRatio-15,hgt/devicePixelRatio-35);ctx.stroke();ctx.strokeStyle='#42e0b0';ctx.lineWidth=2;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(sx(p[0]),sy(p[1])):ctx.moveTo(sx(p[0]),sy(p[1])));ctx.stroke();ctx.fillStyle='#4bd8e8';pts.forEach(p=>{ctx.beginPath();ctx.arc(sx(p[0]),sy(p[1]),4,0,Math.PI*2);ctx.fill()})}
function renderWorkflow(){let a=read('workflow',['Input','Quality Control','Processing','Analysis','Visualization','Interpretation','Output']);$('#workflowNodes').innerHTML=a.map((x,i)=>`<div class="wf-node"><span>${i+1}</span><b>${esc(x)}</b></div>`).join('')}
function loadMicro(files){[...files].filter(f=>f.type.startsWith('image/')).forEach(f=>{let r=new FileReader();r.onload=()=>{let d=$('#microGrid'),card=document.createElement('figure');card.className='media';card.innerHTML=`<img src="${r.result}" alt="Microscopy image"><figcaption>${esc(f.name)}</figcaption>`;d.prepend(card)};r.readAsDataURL(f)})}

function initGlobalScienceBackground(){
  const canvas=document.getElementById('globalScienceCanvas'); if(!canvas)return;
  const ctx=canvas.getContext('2d',{alpha:true}); if(!ctx)return;
  const reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  let W=innerWidth,H=innerHeight,dpr=1,pts=[],raf=0,t0=performance.now(),mx=.5,my=.5;
  const colors=['66,224,176','75,216,232','169,120,255'];
  function resize(){
    dpr=Math.min(2.5,window.devicePixelRatio||1);W=innerWidth;H=innerHeight;
    canvas.width=Math.floor(W*dpr);canvas.height=Math.floor(H*dpr);canvas.style.width=W+'px';canvas.style.height=H+'px';
    ctx.setTransform(dpr,0,0,dpr,0,0);
    const n=Math.max(55,Math.min(150,Math.floor(W*H/11500)));
    pts=Array.from({length:n},()=>({x:Math.random()*W,y:Math.random()*H,vx:(Math.random()-.5)*.12,vy:(Math.random()-.5)*.12,r:.35+Math.random()*1.35,p:Math.random()*Math.PI*2,z:.3+Math.random()*.9,c:colors[Math.floor(Math.random()*colors.length)]}));
  }
  function draw(now){
    ctx.clearRect(0,0,W,H);const time=(now-t0)*.001;
    const px=(mx-.5)*18,py=(my-.5)*18;
    ctx.save();ctx.translate(px,py);ctx.globalCompositeOperation='lighter';
    // Deep-space molecular particles and proximity bonds
    for(const p of pts){p.x+=p.vx;p.y+=p.vy;if(p.x<-10)p.x=W+10;if(p.x>W+10)p.x=-10;if(p.y<-10)p.y=H+10;if(p.y>H+10)p.y=-10;p.p+=.006;
      const a=(.12+.16*(.5+.5*Math.sin(p.p+time)))*p.z;ctx.fillStyle=`rgba(${p.c},${a})`;ctx.beginPath();ctx.arc(p.x,p.y,p.r*p.z,0,Math.PI*2);ctx.fill();
    }
    for(let i=0;i<pts.length;i++){const a=pts[i];for(let j=i+1;j<pts.length;j++){const b=pts[j],dx=a.x-b.x,dy=a.y-b.y,d=Math.hypot(dx,dy);if(d<120){ctx.strokeStyle=`rgba(75,216,232,${(1-d/120)*.065*a.z})`;ctx.lineWidth=.45;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}}}
    // Slow scientific orbital rings
    ctx.globalAlpha=.11;ctx.strokeStyle='#42e0b0';ctx.lineWidth=.7;
    for(let k=0;k<3;k++){const cx=W*(.2+.3*k),cy=H*(.2+.27*Math.sin(time*.07+k)),rx=120+55*k,ry=42+18*k;ctx.save();ctx.translate(cx,cy);ctx.rotate(time*(.015+k*.006));ctx.beginPath();ctx.ellipse(0,0,rx,ry,0,0,Math.PI*2);ctx.stroke();ctx.restore();}
    // A faint travelling scan beam gives the page continuous life without flashing
    const beam=((time*.018)%1)*(W+400)-200;ctx.globalAlpha=.055;ctx.fillStyle='#42e0b0';ctx.fillRect(beam,0,2,H);ctx.fillRect(beam+8,0,1,H);
    ctx.restore();
    if(!reduced)raf=requestAnimationFrame(draw);
  }
  addEventListener('pointermove',e=>{mx=e.clientX/W;my=e.clientY/H},{passive:true});
  addEventListener('resize',resize,{passive:true});resize();draw(performance.now());
}

function initScienceMotion(){
  const canvas=document.getElementById('scienceCanvas'); if(!canvas)return;
  const ctx=canvas.getContext('2d'); if(!ctx)return;
  const host=canvas.parentElement; let W=0,H=0,dpr=1,pts=[],raf=0,mouse={x:.5,y:.5};
  const reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  function resize(){dpr=Math.min(2,devicePixelRatio||1);W=host.clientWidth;H=host.clientHeight;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0);let n=Math.max(28,Math.min(70,Math.floor(W*H/9000)));pts=Array.from({length:n},(_,i)=>({x:Math.random()*W,y:Math.random()*H,vx:(Math.random()-.5)*.22,vy:(Math.random()-.5)*.22,r:Math.random()*1.5+.4,p:Math.random()*Math.PI*2}));}
  function draw(t){ctx.clearRect(0,0,W,H);ctx.globalCompositeOperation='lighter';
    for(const p of pts){p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>W)p.vx*=-1;if(p.y<0||p.y>H)p.vy*=-1;p.p+=.01;let a=.22+.18*Math.sin(p.p+t*.001);ctx.fillStyle=`rgba(66,224,176,${a})`;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();}
    for(let i=0;i<pts.length;i++){for(let j=i+1;j<pts.length;j++){let a=pts[i],b=pts[j],dx=a.x-b.x,dy=a.y-b.y,d=Math.hypot(dx,dy);if(d<105){ctx.strokeStyle=`rgba(75,216,232,${(1-d/105)*.09})`;ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}}}
    if(!reduced)raf=requestAnimationFrame(draw);
  }
  host.addEventListener('pointermove',e=>{let r=host.getBoundingClientRect();mouse.x=(e.clientX-r.left)/W;mouse.y=(e.clientY-r.top)/H;host.style.setProperty('--mx',((mouse.x-.5)*10).toFixed(2)+'px');host.style.setProperty('--my',((mouse.y-.5)*10).toFixed(2)+'px')},{passive:true});
  window.addEventListener('resize',resize,{passive:true});resize();draw(performance.now());
}
function initReveal(){const sections=document.querySelectorAll('.section');if(!('IntersectionObserver' in window)){sections.forEach(s=>s.classList.add('in-view'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in-view')}),{threshold:.08});sections.forEach(s=>io.observe(s));}
init();
initGlobalScienceBackground();
initScienceMotion();
initReveal();
})();
