const state={profile:{},projects:[],library:[],research:[],timeline:[],content:[]};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
async function json(path,fallback){try{const r=await fetch(path,{cache:"no-store"});if(!r.ok)throw 0;return await r.json()}catch{return fallback}}
async function load(){state.profile=await json("profile.json",{});state.projects=await json("projects.json",[]);state.library=await json("library.json",[]);state.research=await json("research.json",[]);state.timeline=await json("timeline.json",[]);state.content=await json("content.json",[]);renderProfile();renderResearch();renderExpertise();renderProjects("all");renderLibrary();renderContent();renderTimeline()}
function renderProfile(){const p=state.profile;const set=(id,v)=>{const e=document.querySelector(id);if(e)e.textContent=v||""};set("#heroLead",p.bio||p.tagline);set("#aboutName",p.name);set("#aboutSummary",p.summary);set("#aboutBio",p.goals);set("#factDegree",p.degree);set("#factLocation",p.location);set("#degreeLine",p.degree)}
function renderResearch(){const e=document.querySelector("#research-grid");e.innerHTML=state.research.map((x,i)=>`<article class="research-card"><span class="card-num">${String(i+1).padStart(2,"0")} / AREA</span><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><small>${esc(x.category||"RESEARCH")} • EXPLORE • LEARN • BUILD</small></article>`).join("")}
function renderExpertise(){const p=state.profile;const g=document.querySelector("#expertise-grid");g.innerHTML=(p.focus||[]).map((x,i)=>`<article class="expertise-card"><span>0${i+1}</span><h3>${esc(x)}</h3><p>${esc((p.skills||[])[i%Math.max(1,(p.skills||[]).length)]||"Developing an interdisciplinary scientific foundation.")}</p></article>`).join("");const tags=(id,a)=>{const e=document.querySelector(id);e.innerHTML=(a||[]).map(x=>`<span>${esc(x)}</span>`).join("")};tags("#lab-skills",p.labSkills);tags("#tools-skills",p.tools);document.querySelector("#principles").innerHTML=(p.principles||[]).map(x=>`<div>↳ ${esc(x)}</div>`).join("")}
function renderProjects(filter){const e=document.querySelector("#project-grid"),xs=state.projects.filter(x=>filter==="all"||x.type===filter);e.innerHTML=xs.map(x=>`<article class="project-card"><span class="card-num">${esc(x.category||"WORK")}</span><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><small>${esc(x.year||"")}</small></article>`).join("")||"<p>No entries yet.</p>"}
function renderLibrary(){const q=(document.querySelector("#search").value||"").toLowerCase().trim(),xs=state.library.filter(x=>`${x.title} ${x.description} ${x.type} ${x.category}`.toLowerCase().includes(q));document.querySelector("#count").textContent=`${xs.length} item${xs.length===1?"":"s"}`;document.querySelector("#library-grid").innerHTML=xs.map(x=>`<a class="library-item" href="${esc(x.file||x.url||"#")}" target="_blank" rel="noopener"><b>${esc(x.title)}</b><span>${esc(x.description||"")}</span><i>${esc(x.type||"RESOURCE")}</i></a>`).join("")||"<p>No matching resources yet.</p>"}
function mediaMarkup(x){if(!x.media)return"";const u=esc(x.media),t=(x.type||"").toLowerCase();if(t.includes("image"))return`<img src="${u}" alt="${esc(x.title)}" loading="lazy">`;if(t.includes("video"))return`<video src="${u}" controls preload="metadata"></video>`;if(t.includes("audio"))return`<audio src="${u}" controls></audio>`;return`<a class="content-file" href="${u}" target="_blank" rel="noopener">Open attached ${esc(x.type||"file")} ↗</a>`}
function renderContent(){const e=document.querySelector("#content-grid"),xs=[...state.content].sort((a,b)=>Number(b.featured)-Number(a.featured)||String(b.date||"").localeCompare(String(a.date||"")));e.innerHTML=xs.map(x=>`<article class="content-card ${x.featured?"featured":""}">${mediaMarkup(x)}<div class="content-body"><div class="content-meta"><span>${esc(x.category||"NOTE")}</span><time>${esc(x.date||"")}</time></div><h3>${esc(x.title)}</h3><p>${esc(x.description||"")}</p>${x.body?`<div class="content-long">${esc(x.body).replace(/\n/g,"<br>")}</div>`:""}</div></article>`).join("")||`<div class="empty-content"><span>01</span><h3>Your next note can live here.</h3><p>Publish a photo, video, document or text entry from the Admin Studio.</p></div>`}
function renderTimeline(){document.querySelector("#timeline").innerHTML=state.timeline.map(x=>`<article class="event"><time>${esc(x.year||x.date||"")}</time><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p></article>`).join("")}
function closeMenu(){const p=document.querySelector("#menuPanel"),b=document.querySelector("#menuBtn");p.classList.remove("open");p.setAttribute("aria-hidden","true");b.classList.remove("open");b.setAttribute("aria-expanded","false");document.body.style.overflow=""}
function openMenu(){const p=document.querySelector("#menuPanel"),b=document.querySelector("#menuBtn");p.classList.add("open");p.setAttribute("aria-hidden","false");b.classList.add("open");b.setAttribute("aria-expanded","true");document.body.style.overflow="hidden"}
document.querySelector("#menuBtn").addEventListener("click",()=>document.querySelector("#menuPanel").classList.contains("open")?closeMenu():openMenu());document.querySelector("#closeMenu").addEventListener("click",closeMenu);document.querySelector("#menuBackdrop").addEventListener("click",closeMenu);document.querySelectorAll(".drawer-nav a").forEach(a=>a.addEventListener("click",closeMenu));document.querySelector("#search").addEventListener("input",renderLibrary);document.querySelectorAll(".filter").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderProjects(b.dataset.filter)}));
const theme=document.querySelector("#theme");function applyTheme(){const light=localStorage.theme==="light";document.body.classList.toggle("light",light);theme.textContent=light?"☾":"☼"}theme.addEventListener("click",()=>{localStorage.theme=document.body.classList.contains("light")?"dark":"light";applyTheme()});applyTheme();
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll(".reveal").forEach(x=>observer.observe(x));document.addEventListener("keydown",e=>{if(e.key==="Escape")closeMenu()});load();