(function(){
'use strict';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const key=k=>`scientificWorkspace:${k}`;
const read=(k,f)=>{try{const v=JSON.parse(localStorage.getItem(key(k)));return v??f}catch{return f}};
const write=(k,v)=>localStorage.setItem(key(k),JSON.stringify(v));
const download=(name,text,type='text/plain')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
const toast=m=>{let t=$('#toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t)}t.textContent=m;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2200)};
let currentExperiment=null;
function setDate(){const x=$('#journalForm input[name="date"]');if(x&&!x.value)x.value=new Date().toISOString().slice(0,10)}
function renderMetrics(){const e=$('#workspaceMetrics');if(!e)return;const exp=read('experiments',[]), journal=read('journal',[]), inv=read('inventory',[]);const metrics=[['Experiments',exp.length,'local drafts'],['Journal',journal.length,'local entries'],['Inventory',inv.length,'local items'],['Workspace tools','30+','browser features']];e.innerHTML=metrics.map(([a,b,c])=>`<div class="metric"><strong>${esc(b)}</strong><span>${esc(a)}</span><small>${esc(c)}</small></div>`).join('')}
function formObject(form){const o={};new FormData(form).forEach((v,k)=>o[k]=String(v));return o}
function renderExperiments(){const e=$('#experimentDrafts');if(!e)return;const xs=read('experiments',[]);e.innerHTML=xs.length?xs.slice().reverse().map((x,i)=>`<article class="saved-item"><div><span class="micro">${esc(x.status||'Draft')}</span><h4>${esc(x.title)}</h4><p>${esc(x.objective||'No objective recorded.')}</p><small>${esc(x.created||'')}</small></div><div><button class="mini-btn" data-exp-view="${xs.length-1-i}">View</button><button class="mini-btn danger" data-exp-del="${xs.length-1-i}">Delete</button></div></article>`).join(''):'<div class="empty">No local experiment drafts yet.</div>'}
function setupExperiments(){const f=$('#experimentForm');if(!f)return;f.addEventListener('submit',e=>{e.preventDefault();const o=formObject(f);o.created=new Date().toLocaleString();const xs=read('experiments',[]);xs.push(o);write('experiments',xs);currentExperiment=o;renderExperiments();renderMetrics();toast('Experiment draft saved locally.')});$('#clearExperimentForm')?.addEventListener('click',()=>{f.reset();setDate()});$('#exportExperiment')?.addEventListener('click',()=>{const o=currentExperiment||formObject(f);const txt=Object.entries(o).map(([k,v])=>`${k.toUpperCase()}\n${v||'—'}`).join('\n\n');download('experiment-draft.txt',txt)});$('#experimentDrafts')?.addEventListener('click',e=>{const v=e.target.closest('[data-exp-view]'),d=e.target.closest('[data-exp-del]');const xs=read('experiments',[]);if(v){const x=xs[Number(v.dataset.expView)];if(x){currentExperiment=x;Object.keys(x).forEach(k=>{const el=f.elements.namedItem(k);if(el)el.value=x[k]||''});toast('Draft loaded.')}}if(d){xs.splice(Number(d.dataset.expDel),1);write('experiments',xs);renderExperiments();renderMetrics();toast('Draft deleted.')}});renderExperiments()}
function renderJournal(){const e=$('#journalList');if(!e)return;const xs=read('journal',[]);e.innerHTML=xs.length?xs.slice().reverse().map((x,i)=>`<article class="journal-item"><div class="journal-date">${esc(x.date||'')}</div><div><span class="micro">${esc(x.type||'Entry')}</span><h4>${esc(x.title)}</h4><p>${esc(x.body)}</p></div><button class="mini-btn danger" data-jdel="${xs.length-1-i}">×</button></article>`).join(''):'<div class="empty">Your local scientific journal is empty.</div>'}
function setupJournal(){const f=$('#journalForm');if(!f)return;setDate();f.addEventListener('submit',e=>{e.preventDefault();const x=formObject(f);const xs=read('journal',[]);xs.push(x);write('journal',xs);f.reset();setDate();renderJournal();renderMetrics();toast('Journal entry saved locally.')});$('#clearJournal')?.addEventListener('click',()=>{if(confirm('Clear all local journal entries?')){localStorage.removeItem(key('journal'));renderJournal();renderMetrics()}});$('#journalList')?.addEventListener('click',e=>{const b=e.target.closest('[data-jdel]');if(!b)return;const xs=read('journal',[]);xs.splice(Number(b.dataset.jdel),1);write('journal',xs);renderJournal();renderMetrics()});renderJournal()}
const nodes=[['Molecular Biology','DNA, RNA, replication, transcription and genetics.'],['Nanobiotechnology','Nanoscale materials, interfaces and biosensing.'],['Bioinformatics','Sequence analysis, databases and computational workflows.'],['Microbiology','Cultivation, staining, growth and microbial observation.'],['Data Analysis','Graphs, statistics, regression and growth curves.'],['Microscopy','Imaging, observation, scale and metadata.'],['Literature','Papers, reading notes and references.'],['Experimentation','Questions, variables, controls and results.'],['Scientific Communication','Figures, presentations, posters and CV.']];
function renderKnowledge(){const g=$('#knowledgeGraph');if(!g)return;g.innerHTML=nodes.map((n,i)=>`<button class="knowledge-node n${i}" data-kn="${i}">${esc(n[0])}</button>`).join('<span class="knowledge-link">↔</span>');g.addEventListener('click',e=>{const b=e.target.closest('[data-kn]');if(!b)return;const [name,desc]=nodes[Number(b.dataset.kn)];$('#knowledgeDetail').innerHTML=`<span class="micro">TOPIC</span><h3>${esc(name)}</h3><p>${esc(desc)}</p><div class="tags"><span>${esc(name)}</span><span>Research</span><span>Documentation</span></div>`})}
const evidence=[['Molecular Biology','Coursework → notes → sequence tools'],['Microbiology','Coursework → growth analysis → lab documentation'],['Bioinformatics','Sequence utilities → data analysis → reproducible workflows'],['Scientific Communication','Presentations → figures → academic CV'],['Data Analysis','OD/time data → plots → regression → interpretation'],['Research Documentation','Experiments → journal → protocols → evidence']];
function renderEvidence(){const e=$('#evidenceGrid');if(!e)return;e.innerHTML=evidence.map((x,i)=>`<article class="evidence-card"><span class="micro">0${i+1}</span><h3>${esc(x[0])}</h3><div class="evidence-flow">${esc(x[1])}</div><div class="evidence-bar"><i style="width:${45+i*8}%"></i></div></article>`).join('')}
function renderInventory(){const e=$('#inventoryList');if(!e)return;const q=($('#inventorySearch')?.value||'').toLowerCase();const xs=read('inventory',[]).filter(x=>`${x.item} ${x.category} ${x.status} ${x.notes}`.toLowerCase().includes(q));e.innerHTML=xs.length?xs.slice().reverse().map((x,i)=>`<article class="inventory-item"><div><span class="micro">${esc(x.category)}</span><h4>${esc(x.item)}</h4><p>${esc(x.notes||'')}</p></div><div><b>${esc(x.status)}</b><button class="mini-btn danger" data-idel="${read('inventory',[]).length-1-i}">Delete</button></div></article>`).join(''):'<div class="empty">No matching inventory items.</div>'}
function setupInventory(){const f=$('#inventoryForm');if(!f)return;f.addEventListener('submit',e=>{e.preventDefault();const xs=read('inventory',[]);xs.push(formObject(f));write('inventory',xs);f.reset();renderInventory();renderMetrics();toast('Inventory item added locally.')});$('#inventorySearch')?.addEventListener('input',renderInventory);$('#clearInventory')?.addEventListener('click',()=>{if(confirm('Clear local inventory?')){localStorage.removeItem(key('inventory'));renderInventory();renderMetrics()}});$('#inventoryList')?.addEventListener('click',e=>{const b=e.target.closest('[data-idel]');if(!b)return;const xs=read('inventory',[]);xs.splice(Number(b.dataset.idel),1);write('inventory',xs);renderInventory();renderMetrics()});renderInventory()}
function setupViz(){const canvas=$('#vizCanvas');if(!canvas)return;const saved=read('vizNodes',null);if(saved)canvas.innerHTML=saved.map((x,i)=>`<div class="viz-node">${esc(x)}</div>${i<saved.length-1?'<span>→</span>':''}`).join('');$('#addVizNode')?.addEventListener('click',()=>{const v=$('#vizLabel')?.value.trim();if(!v)return;const arr=read('vizNodes',['Question','Method','Data','Result']);arr.push(v);write('vizNodes',arr);renderViz();$('#vizLabel').value='';toast('Node added.')});$('#clearViz')?.addEventListener('click',()=>{write('vizNodes',['Question','Method','Data','Result']);renderViz()});function renderViz(){const a=read('vizNodes',['Question','Method','Data','Result']);canvas.innerHTML=a.map((x,i)=>`<div class="viz-node">${esc(x)}</div>${i<a.length-1?'<span>→</span>':''}`).join('')}renderViz();const n=$('#figureNotes');if(n)n.value=localStorage.getItem(key('figureNotes'))||'';$('#saveFigureNotes')?.addEventListener('click',()=>{localStorage.setItem(key('figureNotes'),n.value);toast('Figure notes saved locally.')});$('#clearFigureNotes')?.addEventListener('click',()=>{n.value='';localStorage.removeItem(key('figureNotes'))})}
async function getData(){const files=['profile.json','projects.json','research.json','library.json','publications.json','protocols.json','labnotes.json','content.json'];const out=[];for(const f of files){try{const r=await fetch(f,{cache:'no-store'});if(r.ok){const j=await r.json();out.push({source:f,data:j})}}catch{}}return out}
function flatten(x){if(Array.isArray(x))return x; if(x&&typeof x==='object'){return Object.values(x).flatMap(v=>flatten(v))} return []}
async function setupGlobalSearch(){const input=$('#globalSearchInput'),res=$('#globalSearchResults');if(!input||!res)return;const sections=$$('.section[id]').map(x=>({title:x.querySelector('h2')?.textContent.trim()||x.id,desc:x.querySelector('.section-kicker')?.textContent.trim()||'Section',href:'#'+x.id,type:'Section'}));const data=await getData();const docs=[];for(const src of data){for(const x of flatten(src.data)){if(x&&typeof x==='object'){const title=x.title||x.name||x.topic||x.heading;if(title)docs.push({title,desc:x.description||x.summary||x.abstract||x.body||x.content||src.source,href:'#'+(src.source==='projects.json'?'projects':src.source==='publications.json'?'literature':src.source==='protocols.json'?'protocols':src.source==='labnotes.json'?'notebook':'field-notes'),type:src.source.replace('.json','')})}}}const all=[...sections,...docs,{title:'Bioinformatics toolkit',desc:'Sequence analysis and molecular utilities',href:'#biotools',type:'Tool'},{title:'Data Studio',desc:'Scientific plotting and analysis',href:'#data-studio',type:'Tool'},{title:'Lab calculators',desc:'Dilution, molarity, centrifugation and Beer–Lambert',href:'#calculators',type:'Tool'}];function render(q=''){q=q.trim().toLowerCase();const xs=q?all.filter(x=>`${x.title} ${x.desc} ${x.type}`.toLowerCase().includes(q)):all.slice(0,12);res.innerHTML=xs.slice(0,30).map(x=>`<a class="global-result" href="${esc(x.href)}"><span class="micro">${esc(x.type)}</span><strong>${esc(x.title)}</strong><small>${esc(String(x.desc).replace(/\s+/g,' ').slice(0,150))}</small></a>`).join('')||'<div class="empty">No results found.</div>'}input.addEventListener('input',()=>render(input.value));render('')}
function wireWorkspaceLinks(){[['newExperimentBtn','#experiment-builder'],['newJournalBtn','#journal'],['focusSearchBtn','#global-search']].forEach(([id,href])=>$('#'+id)?.addEventListener('click',()=>$(href)?.scrollIntoView({behavior:'smooth'})));}
function init(){try{renderMetrics();setupExperiments();setupJournal();renderKnowledge();renderEvidence();setupInventory();setupViz();setupGlobalSearch();wireWorkspaceLinks();}catch(e){console.error('Scientific Workspace module:',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
